"""omitted the name column

Revision ID: 014d1b7506c2
Revises: 12b2be3ed1bd
Create Date: 2023-07-06 18:39:20.051632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014d1b7506c2'
down_revision = '12b2be3ed1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showroom', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('showroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
